{
 "title": "PC Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Single Logical Cors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Core #1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PC_BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Core 1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percentage\")"
    }
   ]
  },
  {
   "title": "Core #2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PC_BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Core 2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percentage\")"
    }
   ]
  },
  {
   "title": "Core #3",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PC_BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Core 3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percentage\")"
    }
   ]
  },
  {
   "title": "Core #4",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PC_BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Core 4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percentage\")"
    }
   ]
  },
  {
   "title": "Core #5",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PC_BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Core 5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percentage\")"
    }
   ]
  },
  {
   "title": "Core #6",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PC_BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Core 6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percentage\")"
    }
   ]
  },
  {
   "title": "Core #7",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PC_BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Core 7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percentage\")"
    }
   ]
  },
  {
   "title": "Core #8",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PC_BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Core 8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percentage\")"
    }
   ]
  },
  {
   "title": "Core #9",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PC_BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Core 9\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percentage\")"
    }
   ]
  },
  {
   "title": "Core #10",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PC_BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Core 10\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percentage\")"
    }
   ]
  },
  {
   "title": "Core #11",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PC_BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Core 11\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percentage\")"
    }
   ]
  },
  {
   "title": "Core #12",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PC_BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Core 12\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percentage\")"
    }
   ]
  }
 ]
}